name: Build and Push to GCR

on:
  push:
    branches:
      - "master"
      - "mikhail/rye-416-store-builder-deploy-image-on-push-to"

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: us-central1-docker.pkg.dev/store-builder-356007/rye/store-builder

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup gcloud CLI
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCR_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build the Docker image
      - name: Build
        run: |
          docker build -f Dockerfile.prod  --tag "$IMAGE":"latest" --tag "$IMAGE":"$GITHUB_SHA" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker image push "$IMAGE":"latest"
          docker image push "$IMAGE":"$GITHUB_SHA"
